// Transcript reader: mmap backward scan for the previous user message,
// extracted from main.rs (XUD7YUZH modularization step 12).

// ============================================================================
// Transcript reader — mmap backward scan
// ============================================================================

/// Extract the 2nd most recent user message from a JSONL transcript file.
///
/// Uses mmap + backward newline scan — zero-copy, constant memory (~0 alloc
/// for non-user lines), handles 559MB transcripts with 3.6MB base64 image
/// lines in ~3ms.
///
/// Algorithm:
/// 1. mmap the file (zero-copy, OS-managed paging)
/// 2. Scan backwards from EOF for newline positions
/// 3. For each line: check first 512 bytes for "human"/"user" (pre-filter)
/// 4. Skip tool-result messages (v2.1.85+: toolUseResult/sourceToolAssistantUUID)
/// 5. Only parse lines that pass pre-filter with serde_json
/// 6. Return the 2nd user message text (1st is current prompt)
pub(crate) fn extract_prev_user_message(transcript_path: &str) -> String {
    use memmap2::Mmap;
    use std::time::Instant;

    let path = std::path::Path::new(transcript_path);
    if !path.exists() {
        return String::new();
    }

    let file = match std::fs::File::open(path) {
        Ok(f) => f,
        Err(_) => return String::new(),
    };

    let metadata = match file.metadata() {
        Ok(m) => m,
        Err(_) => return String::new(),
    };

    if metadata.len() == 0 {
        return String::new();
    }

    // Safety: file is read-only, no concurrent writes expected during hook execution
    let mmap = match unsafe { Mmap::map(&file) } {
        Ok(m) => m,
        Err(_) => return String::new(),
    };

    let start = Instant::now();
    let deadline_ms = 800u128; // 800ms time budget
    let data = &mmap[..];
    let mut pos = data.len();
    let mut user_messages_found = 0u32;
    let max_result_len = 4000; // Cap returned text

    // Scan backwards for newlines, peek at each line for pre-filter
    while pos > 0 {
        if start.elapsed().as_millis() > deadline_ms {
            return String::new(); // Time budget exceeded
        }

        // Find previous newline
        let nl = match data[..pos].iter().rposition(|&b| b == b'\n') {
            Some(p) => p,
            None => 0, // Start of file
        };

        let line_start = if nl == 0 && data[0] != b'\n' { 0 } else { nl + 1 };
        let line = &data[line_start..pos];
        pos = if nl == 0 && data[0] != b'\n' { 0 } else { nl };

        if line.len() < 20 {
            continue;
        }

        // Pre-filter: peek at first 512 bytes for role markers.
        // Multi-MB base64 image lines are skipped without reading past byte 512.
        let peek_len = std::cmp::min(512, line.len());
        let peek = &line[..peek_len];
        if !contains_subsequence(peek, b"\"human\"") && !contains_subsequence(peek, b"\"user\"") {
            continue;
        }

        // Skip tool-result messages (v2.1.85+): auto-generated by tool execution,
        // not user-typed prompts. Pre-filter avoids parsing multi-MB tool output.
        if contains_subsequence(peek, b"\"toolUseResult\"")
            || contains_subsequence(peek, b"\"sourceToolAssistantUUID\"")
        {
            continue;
        }

        // This line likely contains a user message — parse it
        let entry: serde_json::Value = match serde_json::from_slice(line) {
            Ok(v) => v,
            Err(_) => continue,
        };

        // Extract user text from {"message": {"role": "human"|"user", "content": ...}}
        let msg = match entry.get("message") {
            Some(m) => m,
            None => continue,
        };
        let role = msg.get("role").and_then(|r| r.as_str()).unwrap_or("");
        if role != "human" && role != "user" {
            continue;
        }

        // Belt-and-suspenders: skip tool-result entries even if the peek
        // pre-filter missed (field appears after byte 512 in large entries)
        if entry.get("toolUseResult").is_some()
            || entry.get("sourceToolAssistantUUID").is_some()
        {
            continue;
        }

        let text = match msg.get("content") {
            Some(serde_json::Value::String(s)) => s.trim().to_string(),
            Some(serde_json::Value::Array(arr)) => {
                // Content blocks: [{"type": "text", "text": "..."}, ...]
                let mut parts = Vec::new();
                for block in arr {
                    if let Some(t) = block.get("text").and_then(|t| t.as_str()) {
                        parts.push(t);
                    }
                }
                parts.join(" ").trim().to_string()
            }
            _ => continue,
        };

        if text.is_empty() {
            continue;
        }

        user_messages_found += 1;
        // Skip 1st (current prompt already in transcript), return 2nd
        if user_messages_found >= 2 {
            if text.len() > max_result_len {
                // Truncate at a valid UTF-8 char boundary to avoid panic
                // on multi-byte characters (CJK, emoji, accented text)
                let mut end = max_result_len;
                while end > 0 && !text.is_char_boundary(end) {
                    end -= 1;
                }
                return text[..end].to_string();
            }
            return text;
        }
    }

    String::new()
}

/// Fast subsequence check (avoids allocating a Window iterator for short needles)
#[inline]
pub(crate) fn contains_subsequence(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || needle.len() > haystack.len() {
        return needle.is_empty();
    }
    haystack.windows(needle.len()).any(|w| w == needle)
}
